City-of-Helsinki/employment-services-ui

- src/components/pageTemplates/NodeLandingPage.tsx
A check was added so If hero is available the title of landing page will be printed only inside the hero component. in hero's absence, the title of the page will be printed on top of the page.
> THF-267: landing page title will be printed once

- styles/globals.scss
Change that list of links: link with image shows only two items side by side on basic page. Can be found from Koulutusneuvonta page.
> THF-307: list of links with image on basic page

- pages/[...slug].tsx
- src/components/events/EventList.tsx
- src/components/news/NewsList.tsx
- src/lib/helpers.ts
- Updated React to use path alias coming from Drupal instead of using translated paths.
- Works only with Finnish translations.
- Events should have now "Tapahtumakalenteri" as the parent, hence the breadcrumb remains up-to-date.
> THF-299: Events breadcrumb

- src/components/navigation/Header.tsx
- Clicking the logo will now point to the site's front page.
- Works with language prefix
> THF-311: Adding front page link for the site logo

- src/hooks/useAnalytics.ts
- Updated cookie consent component with CookieDomain option to prevent hel.fi site to delete unknown cookie.
> THF-377: Setting cookieDomain instead using global setting.

- src/components/consentInfo/ConsentInfo.tsx
- Fixes an error of "Target container is not a DOM element." when navigating to cookies page from consents info banner link
> THF-406: Fixing app crash when navigating to cookies page.

- src/components/news/NewsList.tsx
- src/lib/params.ts
Bring only published news to the news page.
How to test:
- Create new article at least one published and one unpublished. https://drupal-tyollisyyspalvelut-helfi.docker.so/node/add/article
- The news list should now show only published articles http://localhost:3000/ajankohtaista/uutiset
> THF-463: Added status to news list and filter by the status

- src/components/consentInfo/ConsentInfo.tsx
Cookie sv and en link not working on react and share component. The link adding en/cookies or sv/cookies end of the link. Please see the picture below. The link should be http://localhost:3000/en/cookies.
How to test:
- Take the branch and repeat the steps and you should end up to the cookie page
- Open page and accept only essential cookies 
- Cookies can be change on page http://localhost:3000/cookies
- Go to example page en page http://localhost:3000/en/official-matters/welcome-client
- Note!! Page needs to be something else than http://localhost:3000
- Scroll  down to the react and share component (image  below)
- Click the button 
- You should get the cookies page
- Try also with sv page
> Thf 455 cookies sv en url

- src/components/pageTemplates/NodeEventPage.tsx
- src/lib/params.ts
Added location extra info to the event pages.
**how to test:**
- Go to page (or if you find some other page with field_location_extra_info) http://localhost:3000/ajankohtaista/tapahtumat/sol-rekrytoi-logistiikka-alalle
-  you should see under location extra info with exclamation mark icon.
- Take some other page event page example http://localhost:3000/ajankohtaista/tapahtumat/tyoelamavalmennusta-itakeskuksessa-40 and you should see the location extra info and icon there.
> Thf 416 location extra info

- src/components/hero/hero.module.scss
Hero's left edge of the picture came to the surface if picture was zoomed or from a big screen. Given marging-left to span surrounding the img element. Had to use !important to override the element style attribute.
how to test:
- Verify the problems by going to [tyollisyyspalvelut](https://tyollisyyspalvelut.hel.fi/) and zoom the hero element picture. 
- then do the same in the UI with this branch. You shouldn’t  see the lines any more.
> Give margin to hero left

- src/components/pageTemplates/NodeArticlePage.tsx
- src/lib/params.ts
Publication date field added to article content type.
How to test:
- Related PR -> [THF-446-published-date-for-articles-drupal](https://github.com/City-of-Helsinki/drupal-employment-services/pull/123)
- Run drupal site branch with introductions  `THF-446-published-date-for-articles-drupal` 
- Create new article page on Drupal https://drupal-tyollisyyspalvelut-helfi.docker.so/node/add
- Check that article has date under page title.
- Create new article https://drupal-tyollisyyspalvelut-helfi.docker.so/node/add and scheduled publication date for next day.
- See next day that the date underneath title has changed to the publication date.
Developer:
Add console.log('node') NodeArticlePage.tsx file row 13 and open the created article page. You should see published_at field in the console.
> Thf 446 published date for articles UI

- pages/api/events-tags.ts
Drupal tags didn't bring the filtering to the UI. The tag were fetch from wrong field.
Note that when languages are added to tags this may need fixing.
How to test:
- Run this branch with Drupal branch https://github.com/City-of-Helsinki/drupal-employment-services/pull/128
- See that you can see the filtering tags on even page and use them for filtering. http://localhost:3000/ajankohtaista/tapahtumat
-
> Thf 470  linked event tags UI

- pages/api/events-tags.ts
Restore keyword value. The error what was fixed was only in local environment.
How to test:
- if the branch not working on you local environment 
- On your Drupal project run commands below
- run to clear electric search `curl -X DELETE http://localhost:9200/events_\*`
- `make shell`
-  run reindexing `drush search-api-reindex`
- run indexing `drush search-api:index`
- check your http://localhost:3000/ajankohtaista/tapahtumat
- you should now see the filtering tag above the events.
> THF-470: restore keyword value

- public/locales/en/common.json
- public/locales/fi/common.json
- public/locales/sv/common.json
- src/components/pageTemplates/NodeEventPage.tsx
- src/lib/params.ts
Created new sing up button to the event page. Button is only shown if the linked event has sing up url.
How to test:
- This branch need to be tested with branch https://github.com/City-of-Helsinki/drupal-employment-services/pull/129
- follow the how to test instructions from branch below
- go to page http://localhost:3000/ajankohtaista/tapahtumat/testitapahtuma
- you should see the new sing up button end of the page.
- go to event and you should not see the button https://tyollisyyspalvelut-ui.test.hel.ninja/ajankohtaista/tapahtumat/helsinki-info-neuvoo-itakeskuksessa-9
> THF-416. Add sing up button to the event pages

- src/components/ContentMapper.tsx
- src/components/navigation/Sidebar.tsx
- src/components/pageTemplates/NodeBasicPage.tsx
- src/components/tprUnits/UnitsList.tsx
- src/lib/helpers.ts
- src/lib/types.ts
TPR units were wanted to be same order as they are on side navigation.  First we loop the menu object and get the array from it. We then sort the units by the order of the array from the menu object.
How to test:
- Check out this branch.
- go to http://localhost:3000/yhteystiedot/toimipisteet
- check that the offices in same order as they are in menu. 
- You need to check all languages.
- Then go to main menu edit and change order of the offices.
- https://drupal-tyollisyyspalvelut-helfi.docker.so/admin/structure/menu/manage/main
- check again that the order is same as it is on navigation.
- You need to check all languages.
- Add you own menu item under office.
- check that the new item don’t mix the order.
- You need to check all languages.
> THF-329: Change office list order by menu

- next.config.js
- pages/_app.tsx
- pages/cookies.tsx
- src/hooks/useAnalytics.ts
This PR adds the cookie domain from env variables to the modal and cookie information page. Should fix the issue with the domain being set to `.hel.fi` or `.hel.ninja`.
**To test**
- Checkout branch
- Add this line to to your `.env.local` file: `COOKIE_DOMAIN=localhost` and run `yarn dev`
- Open this page: http://localhost:3000/cookies (this is easier to test in a private browsing window)
- Accept all cookies from the popup. This should reload the page, after which all the cookies should be accepted on the page too.
- Go to http://localhost:3000/tyonhaku and scroll down. The React & Share banner should be visible
- Delete all cookies and reload the page. The cookie popup should appear again and the React & Share banner should show a disclaimer about cookies not being accepted
- Go to the …
> THF-459: Add cookie domain setting to modal and cookies page

- src/components/news/NewsList.tsx
- src/lib/params.ts
- src/lib/ssr-api.ts
Short list functionality now works on news list paragraph. When short list is selected the list brings 4 first published article to the list without the "show more" button. Added background drop-down selection to the news list paragraph so we can create short news list to the pages with background. When background selection is left blank the background colour is white. 
**question**
src/lib/ssr-api.ts I added `.addFilter("status", "1")` to the rows 71 and 84. to filter only published news. Earlier I have added `.filter((newsArticle: News) => newsArticle.status !== false)` in file src/components/news/NewsList.tsx to make sure that we get only published news. Should I remove the earlier added filter `.filter((newsArticle: News) => newsArticle.status !== false)` or leave it there. It's …
> Thf 454 news short list

- src/lib/params.ts
Link of list Paragraph wasn’t working on Article page. Added link of list and link of items paragraphs (which is inside the list of links) to the article page. 
how to test:
- verify the bug first in develop branch
- create new article and add link-of-list paragraph 
- you should get an error after saving the page
- switch to the branch
- go to the created article and you should not get the error
> Thf 486 link of list fix

- pages/[...slug].tsx
- src/lib/helpers.ts
Moved getLanguageLinks to slug so that  we are able to make getResource call vie drupal server.
How to test:
- run `yarn build` and see that you don't have any errors
- then check few pages to see that the pages work.
> THF-496: Move getLanguageLinks to slug

- src/components/accordion/accordion.module.scss
Changed  accordion body font to same as accordion description.
How to test:
Go to page:
https://tyollisyyspalvelut.hel.fi/tyonhaku/apua-tyonhakuun/miten-loydan-toita
See that the main body text and second accordion body text are same size L
> THF-500: change accordion body to follow text body size

- src/components/hero/hero.module.scss
Hero header text wasn't working in Swedish. Added Hyphens to cut the word when on mobile. 
How to test:
- Go to main page http://localhost:3000/sv
- try the page with Developer tools and mobile size screen
- see that the layout looks same all languages
> THF-510: Add hyphens: auto

- pages/[...slug].tsx
- src/components/layout/Layout.tsx
- src/components/navigation/Breadcrumb.tsx
- src/components/navigation/Header.tsx
- src/components/navigation/Sidebar.tsx
- src/components/navigation/navigation.module.scss
- src/components/pageTemplates/NodeBasicPage.tsx
- src/components/pageTemplates/NodeTprUnitPage.tsx
- src/lib/helpers.ts
- src/lib/types.ts
Made Drupal follow preview IFrame's navigation url
How to test:
- go to https://drupal-tyollisyyspalvelut-helfi.docker.so/
- Navigate from Iframe Navigation to some other page than fron page. 
- The Drupal parent page should now follow the link from previews IFrame. 
- Go to https://drupal-tyollisyyspalvelut-helfi.docker.so/yhteystiedot/toimipisteet or other page that have sidebar
- Clicking a sidebar link. The link should take you right place and change the Drupal page url as well
Test also the breadcrumb
- the the appearance shouldn’t have changed
- The text should be black with any hover effect
- The pointer should be pointer as in other links.
- Next.js you should not have any changes
- Go to Drupal and some article
- Navigate back to Current matter page
- Drupal parent page url …
> THF-469: preview functionality to nav

- src/components/navigation/Breadcrumb.tsx
- src/components/navigation/navigation.module.scss
Changes for breadcrumbs. HDS link has build in span. Removed extra span. 
Test also the breadcrumb
the the appearance shouldn’t have changed
The text should be black with any hover effect
The pointer should be pointer as in other links.
Next.js you should not have any changes
Go to Drupal and some article
Navigate back to Current matter page
Drupal parent page url should go to this page.
> THF-469: Remove span from link

- src/components/ContentMapper.tsx
- src/components/accordion/Accordion.tsx
- styles/globals.scss
Accordion element html text had unwanted margins. Added new class from accordion component as props which is passed to contentMapper to over writing the margins from component css class. 
How to test: 
- Go to test page: https://tyollisyyspalvelut-ui.test.hel.ninja/accordion-testi
- Create basic page on local and add same components 
- The accordion shouldn’t have big margin 
- Other components should look exactly same
> THF-319: fix accordion margin

- next-i18next.config.js
- public/locales/ru/common.json
- public/locales/so/common.json
- public/locales/uk/common.json
- src/hooks/useAnalytics.ts
- src/lib/helpers.ts
Added support f or the other languages:
How to test: 
Test this branch with branch THF-523-other-languages.
- Create pages with languages uk, ru and so.
- Check that you don't get any errors when you create the page.
> THF-523: Add support for ru, so and uk

- src/components/navigation/navigation.module.scss
Fixed breadcrumbs path focus. 
How to test:
- go to page which have breadcrumbs example http://localhost:3000/en/contact-information/phone-services
- press one of the breadcrumb link
- you should see blue border when the link has focus
> Thf 551 breadcrumbs path focus

- next.config.js
- pages/404.tsx
- pages/[...slug].tsx
- pages/cookies.tsx
- pages/index.tsx
- src/components/events/events.module.scss
- src/components/navigation/Footer.tsx
- src/lib/helpers.ts
- src/lib/types.ts
Fixed footer problems when getting to 404 page and fixed footer cookies problems. Also fixed redirect to ru and so frontpages.
How to test:
- When changing to this branch -->  restart next if you local environment is on.
- Try url http://localhost:3000/ru and http://localhost:3000/so
-> You should get yourself onto ru and so front pages
- Stay on the last front page.
- See that the footer has cookies url en/cookies
- Write to the browser's url place example http://localhost:3000/ru/helloworld (page that doesn't exist)
- the 404 page should have en footer example en/about rather than node/4567 and all the footer links should work.
> THF-566: correct footer, cookies and redirect

- pages/api/events-tags.ts
- src/components/events/Events.tsx
- src/components/events/events.module.scss
- src/lib/helpers.ts
- src/lib/types.ts
Added tag disabling if adding the tag wont bring result.
How to test:
- Filter events on page http://localhost:3000/en/current-matters/events
- Choose filter Recruitment of employees you should get few options.
- You should now only have filter Remote event available. Other should be disabled. 
- Try other filter tags as well. 
- Also see that the logic still works. Choose example tag Recruitment of employees and then Remote event. You should only get the events which have both tags.
> THF-482: Disable filter tags if the adding tag doesn't get results.

- src/components/pageTemplates/NodeArticlePage.tsx
When scheduler is used created time will change and publish_at time will stay the same. If we don't use scheduler then we want to see publish_at time.
How to test:
- Test this branch with Drupal back end from this branch https://github.com/City-of-Helsinki/drupal-employment-services/pull/144
- Follow the instructions in the Drupal branch.
- On file src/components/pageTemplates/NodeArticlePage.tsx
- To row 29 put` console.log('node-->', node)`  
-  To row 30 put 
```
const test =
published_at !== null && published_at > created ? 'published_at' : 'created';
```
-  To row 40 put `<p>{test}</p>` .
-  Then create an article page and publish it.
-  You should see with on the page published_at text.
-  Then create a new article page and schedule it to be published 2 min later.
-  Wait 3 min and …
> Thf 572 scheduler UI

- pages/cookies.tsx
- src/components/banner/Banner.tsx
- src/components/consentInfo/ConsentInfo.tsx
- src/components/navigation/Footer.tsx
- src/components/navigation/Header.tsx
- src/components/navigation/Sidebar.tsx
- src/components/pageTemplates/NodeTprUnitPage.tsx
- src/lib/helpers.ts
Changed logical or (`||`) operators to nullish coalescing operator (`??`).
how to test:
- Create a Basic page 
- Create Banner paragraph tot he page.
- First don't give the banner Background color
- Save
- You should have Banner with white background color 
- Go edit the page and change the background color to something else.
- You should now have banner with background color.
- Try Cookies link on footer try with primary languages and with additional languages
- Go to Drupal page and try the cookies banner button with primary languages and with additional languages
- With primary languages you should end up to the cookies page with the language you started and with additional languages you should end up to the English cookies page.
- Try the language switcher should work as before.
- Try …
> THF-445:SonardCloud minor change to coalescing operators

- styles/globals.scss
Fixed landing page accordion element padding.
- Create a landing page with accordion element and check that the element don't have extra padding or margin in it. Compare to https://hds.hel.fi/components/accordion
- Check also that the change hasn't effect to accordion on basic page content type. Example http://localhost:3000/koulutus/opiskelu-tyottomana
> THF-587: fix landing page accordion element

- public/locales/en/common.json
- public/locales/fi/common.json
- public/locales/sv/common.json
- src/components/pageTemplates/NodeEventPage.tsx
- src/components/pageTemplates/eventPage.module.scss
Changed event page content layout. Layout has now 2 columns. The hero element's details content contains date and place fields. The other fields should now be placed in the right column of the content area. Below $breakpoint-m you get only 1 column and the detail are below the event description.
- Go to any event from event page http://localhost:3000/ajankohtaista/tapahtumat
- The Event should now have 2 columns
- Try also mobile and pad screen sizes.
> THF-597: change layout

- src/components/navigationComponents/LanguageSelect.tsx
- src/hooks/useAnalytics.ts
- Changes cookies api default key from Finnish to English
- Added other languages nav languages from english to origin language
- Check that the cookies work on en, fi and sv pages in those languages.
- Check example Russian page and see that the cookies are in English there as well.
> Thf 601 nav languages and cookies

- pages/api/related-events.ts
- public/locales/en/common.json
- public/locales/fi/common.json
- public/locales/sv/common.json
- src/components/dateTime/DateTime.tsx
- src/components/dateTime/DateTimeSimple.tsx
- src/components/dateTime/dateTime.module.scss
- src/components/events/EventList.tsx
- src/components/events/Events.tsx
- src/components/events/RelatedEvents.tsx
- src/components/events/events.module.scss
- src/components/news/NewsList.tsx
- src/components/pageTemplates/NodeEventPage.tsx
- src/lib/client-api.ts
- src/lib/params.ts
- src/lib/ssr-api.ts
- src/lib/types.ts
- Brought a `super_event` field to ui. 
- Created new relates event component. 
- Crated new simple dateTime component and moved datetime component to their own folder,
- The component will show all event dates and times which have the same super_event field as the event you are on. It doesn't show the current event date and time on the list. 
- test with branch `THF-535-super_event-field-to-drupal`
- Find an event that has super event and go to the page 
- You should have the new related events component right side of the page.
- If list has more than 3 event you'll see toggle button. 
- You can toggle the list up and down.
> Thf 535 super event UI

- public/locales/en/common.json
- public/locales/fi/common.json
- public/locales/sv/common.json
- src/components/events/RelatedEvents.tsx
- src/components/pageTemplates/NodeEventPage.tsx
- src/components/pageTemplates/eventPage.module.scss
- src/components/sideContent/SideContent.tsx
- src/components/sideContent/sideContent.module.scss
- src/lib/params.ts
Added field_in_language to the UI in Event page. Created new component for side fields. 
- Test and start with branch https://github.com/City-of-Helsinki/drupal-employment-services/pull/156
- Go to any event page. 
- You should have new field languages with global icon. 
- Note that language field is not translated at the moment. So the text will be in Finnish regardless the page language.
> Added field_in_language

- public/locales/fi/common.json
- src/components/events/RelatedEvents.tsx
- src/components/events/events.module.scss
- src/components/navigationComponents/LanguageSelect.tsx
- src/components/pageTemplates/NodeEventPage.tsx
- src/components/sideContent/SideContent.tsx
- src/hooks/useAnalytics.ts
- Fixed React and share language.
- Fixed Related Event to fetch data when base event changes.
- Fixed empty super_event fields to be shown on the event page
- Fixed languages to have space in all gaps.
- put code below to row 155 on the file useAnalytics.ts
```
- console.log(getConfig().publicRuntimeConfig.REACT_AND_SHARE_FI)
- console.log(getConfig().publicRuntimeConfig.REACT_AND_SHARE_EN)
- console.log(getConfig().publicRuntimeConfig.REACT_AND_SHARE_SV)
```
- and put  `console.log('reactAndShareApiKey', reactAndShareApiKey)` before line `window.rnsData = {`
- And see that the reactAndShareApiKey matches with the language of the page
- Go to some event that has super event.  Try to click some event on the Related event component. You should end up to the page event page and the related …
> THF-604: fix relatedEvent and React and share

- src/components/navigationComponents/LanguageSelect.tsx
Added Drupal to follow next-js navigaation in other languages global list.
- test navigations, breadcrumb and sidenav on Drulas site. You should be able to navigate in Drupal using navigations, breadcrumb and sidenav.
> THF-469: Add preview nav to other languages selection

- src/components/pageTemplates/NodeTprUnitPage.tsx
Changed opening hours object to take only object with type `opening_hours`
- Test all offices http://localhost:3000/yhteystiedot/toimipisteet
- You should have office hours filled in all offices. 
-
> THF-615: get only opening hours object

- src/components/news/NewsList.tsx
When created day is greater than published_at we will show the created date and get right date for scheduled Articles.
1. Navigate to page http://localhost:3000/ajankohtaista/uutiset.
2. In the 'src/components/news/NewsList.tsx' file, insert the following code:
3. `console.log('news', news);`
4. Open the developer tools console tab in your web browser.
5. If your data already contains scheduled articles, you can skip steps 6 and 7.
6. If there are no scheduled articles, create a new article and schedule its publication for two minutes in the future. Save the article.
7. After waiting for two minutes, run the 'cron-run' command.
8. Examine several articles to ensure their 'created date' is earlier than their 'published_at' date. You should see the 'created date' displayed on the page if …
> THF-624: newslist date show created time  when Article is scheduled

- pages/api/events-search.ts
- pages/api/events-tags.ts
- pages/api/events.ts
- public/locales/en/common.json
- public/locales/fi/common.json
- src/components/events/Events.tsx
- src/components/events/events.module.scss
- src/components/eventsComponents/ButtonFilter.tsx
- src/components/eventsComponents/DropdownFilter.tsx
- src/components/eventsComponents/EventListComponent.tsx
- src/components/eventsComponents/ResponsiveFilterMapper.tsx
- src/lib/client-api.ts
- src/lib/helpers.ts
- src/lib/params.ts
- src/lib/types.ts
Changed event and tag fetches to use new event_index. Added language filter
- Testing with branch https://github.com/City-of-Helsinki/drupal-employment-services/pull/177
- http://localhost:3000/ajankohtaista/tapahtumat
- Test first Select language.
- When selecting a Drupal language (fi, en, sv, ru, so, ua), the tags should change to the selected language, and you should receive the same data as you would on the local page. For example, if you are on Finnish pages and you choose English in the filter, you should receive the same data as you would on an English page.
- Additionally, the lang tag on URL  should also change to the selected language. 
- Keep a language selected and add topics.
- The "Select Topic" functionality should work as before.
- The URL tags should always be in …
> THF-637: Added new event_index to event components
