City-of-Helsinki/employment-services-ui

src/Image.js

Could we use something like this?
Adjust the `containerStyle` padding to adjust the aspect ratio. Image should adjust accordingly.

Use img for Image

---

src/CardList.js
src/Paragraphs.tsx
tsconfig.json

Quite crude implementation. Recommend to use this for now and clean up later in the "fine tuning stage" of development.

Fix Koro wave for CardList

---

src/CardList.js
src/SingleCard.js
tsconfig.json

**Fine tune card list alignment**
Automatic width and height for Cards in CardList.
@juha-ylonen-futurice Can you remove the unnecessary width and height properties from Drupal afterwards?
**Fix tsconfig**
Seems like a previous merge caused this problem here.

Fine tune card list alignment & Fix tsconfig

---

server/api/api.ts
server/api/events.ts
server/api/tags.ts
src/components/EventsList.tsx

Improve events filtering. Do the actual search query with tag value instead of just filtering the results.
Get tag filter list from new elastic index tags.

Fix and improve events filtering

---

components/HtmlBlock.tsx
components/content-mapper.tsx
components/layout.tsx
components/node-basic-page.tsx
lib/DRUPAL_API_TYPES.js
lib/params.ts
next-i18next.config.js
package.json
pages/[...slug].tsx
yarn.lock

Basic data flow from JSON:API mapped to components. PoC using HDS component Accordion.

Component data flow

---

styles/globals.css

Heading styles using hds tokens, small headings via "small-text" class for whole page or via "small" class on heading element. Default to small headings in mobile size.

Thf 215 headings

---

pages/[...slug].tsx
src/components/HtmlBlock.tsx
src/components/pageTemplates/NodeBasicPage.tsx
src/lib/params.ts
src/lib/types.ts
styles/globals.scss

- Add lead-in text field
- Add types.ts file for custom types
- Add font-weigths for headings

Thf 178 lead text

---

src/components/ContentMapper.tsx
src/components/HtmlBlock.tsx
src/components/accordion/Accordion.tsx
src/components/pageTemplates/NodeBasicPage.tsx
src/lib/drupalApiTypes.js
src/lib/params.ts
src/lib/types.ts

Add new component for Accordion
Support more accordion fields from Drupal

THF-162: accordion

---

next.config.js
pages/[...slug].tsx
pages/index.tsx
src/components/link/link.module.scss
src/components/listOfLinks/listOfLinks.module.scss
src/components/pageTemplates/NodeLandingPage.tsx
src/lib/helpers.ts
src/lib/params.ts

THF-203: Landing page layout

---

pages/[...slug].tsx
src/components/ContentMapper.tsx
src/components/PreviewAlert.tsx
src/components/hero/Hero.tsx
src/components/hero/hero.module.scss
src/components/pageTemplates/NodeLandingPage.tsx
src/lib/params.ts
src/lib/types.ts

Add hero component and related things
Add revalidation time for 404 pages
Cleaning

THF-147: Hero

---

next.config.js
src/components/hero/Hero.tsx
src/components/listOfLinks/ListOfLinks.tsx
src/lib/helpers.ts

Fix image urls

---

src/components/ContentMapper.tsx
src/components/notification/Notification.tsx
src/components/pageTemplates/NodeBasicPage.tsx
src/components/pageTemplates/NodeLandingPage.tsx
src/lib/drupalApiTypes.js
src/lib/params.ts
src/lib/types.ts

Notification component was created using Notification component of HDS. it has been set to show both at the top of basic and landing pages, and anywhere else within the basic page.

THF-157: notification component

---

next.config.js
src/components/ContentMapper.tsx
src/components/accordion/accordion.module.scss
src/components/banner/banner.module.scss
src/components/hero/hero.module.scss
src/components/liftupWithImage/LiftupWithImage.tsx
src/components/liftupWithImage/liftupWithImage.module.scss
src/components/listOfLinks/ListOfLinks.tsx
src/components/listOfLinks/listOfLinks.module.scss
src/lib/drupalApiTypes.js
src/lib/helpers.ts
src/lib/params.ts
styles/globals.scss
styles/variables.scss

Add liftup with image component and stuff needed for it

THF-248: Liftup with image

---

next.config.js
src/lib/helpers.ts

Start using NEXT_IMAGE_DOMAIN for images to bypass VPN
a bit of cleaning

Start using NEXT_IMAGE_DOMAIN for images to bypass VPN

---

pages/[...slug].tsx
pages/index.tsx
src/components/layout/Layout.tsx
src/components/navigation/Footer.tsx
src/components/navigation/navigation.module.scss
src/lib/types.ts

Footer component.

---

src/components/link/link.module.scss
src/components/listOfLinks/listOfLinks.module.scss

Change Linkbox component styles in List of links component to look more like hel.fi
THF-274: Change list of links link underlining

Fix/THF-271: list of links

---

next-i18next.config.js
next.config.js
pages/index.tsx
public/locales/en/common.json
public/locales/fi/common.json
public/locales/sv/common.json

Make frontpage work
Change footer bottom links hardcoded values

Front page & footer link values

---

src/components/ContentMapper.tsx
src/components/pageTemplates/NodeArticlePage.tsx
src/components/pageTemplates/articlePage.module.scss
src/components/paragraphImage/paragraphImage.module.scss
src/components/quote/Quote.tsx
src/components/quote/quote.module.scss
src/lib/drupalApiTypes.js
src/lib/params.ts

Foundation for Quote component

THF-214: news quote

---

src/lib/drupal-client.ts

Add password for both sentinel and redis nodes.

Add password for both sentinel and redis nodes

---

src/components/ContentMapper.tsx
src/components/events/EventList.tsx
src/components/events/events.module.scss
src/components/pageTemplates/NodeBasicPage.tsx
src/components/pageTemplates/NodeEventPage.tsx
styles/globals.scss

Add styles for showing event list in basic page.
Add new prop pageType for ContentMapper.

THF-300: add event list to basic page

---

src/components/pageTemplates/NodeBasicPage.tsx
src/lib/params.ts
src/lib/types.ts

Sidebar is now hidden if "Hide sidebar" option has been selected.

THF-273: Adding sidebar hidding option for Basic Page

---

src/components/ContentMapper.tsx
src/components/pageTemplates/NodeBasicPage.tsx
src/components/sujoEmbedded/sujoEmbedded.tsx
src/lib/drupalApiTypes.js
src/lib/params.ts
src/lib/types.ts

Adding SUJO Embedded component with option for training listing.

THF-234 Implement SUJO embed

---

pages/[...slug].tsx
src/components/ContentMapper.tsx
src/components/HtmlBlock.tsx
src/components/accordion/Accordion.tsx
src/components/banner/Banner.tsx
src/components/events/EventList.tsx
src/components/events/events.module.scss
src/components/liftupWithImage/LiftupWithImage.tsx
src/components/listOfLinks/ListOfLinks.tsx
src/components/news/NewsList.tsx
src/components/pageTemplates/NodeLandingPage.tsx
src/components/paragraphImage/ParagraphImage.tsx
src/lib/drupalApiTypes.js
src/lib/params.ts
styles/globals.scss

Add support for component background color for Events list and List of links components. To achieve this Container component place was changed in the page structure. Some additional css changes were done to make the new structure work.

THF-298: component bgcolor

---

src/components/events/EventList.tsx

THF-299: Fixing build error coming from coding standard.

---

src/components/mediaImage/MediaImage.tsx
src/components/pageTemplates/NodeTprUnitPage.tsx
src/components/pageTemplates/tprUnitPage.module.scss
src/lib/helpers.ts
src/lib/params.ts
src/lib/types.ts

- TPR Unit have possibility to override Unit's Name and Image, added values comparization and display
- Hide contact information blocks without content

THF-204: Adding display for overriden field values (name, image)

---

src/components/ContentMapper.tsx
src/components/events/EventList.tsx
src/components/mapEmbedded/MapEmbedded.tsx
src/components/pageTemplates/NodeTprUnitPage.tsx
src/lib/drupalApiTypes.js
src/lib/helpers.ts
src/lib/params.ts

- Updated Event List and Unit Map components display

THF-204: TPR Unit page components

---

pages/api/units.ts
public/locales/en/common.json
public/locales/fi/common.json
public/locales/sv/common.json
src/components/ContentMapper.tsx
src/components/mediaImage/MediaImage.tsx
src/components/tprUnits/UnitsList.tsx
src/components/tprUnits/units.module.scss
src/lib/client-api.ts
src/lib/drupalApiTypes.js
src/lib/ssr-api.ts

- Adds API call for TPR Units list from Drupal
- Adds new component for UnitsList

THF-168: Adding TPR Units list component and API calls

---

src/components/events/EventList.tsx

- Landing page should have 3 events
- Basic Page and Unit page should have 2 events

THF-331: Fixed events amount per content type.

---

src/components/pageTemplates/tprUnitPage.module.scss

- Unit pages has now responsively scaling image

THF-322: Updated unit image styles to responsive

---

src/components/navigation/Sidebar.tsx
src/lib/get-menu.ts

How to test:
```
yarn build
yarn start
```
Check if sidebar menu is still missing sometimes or not.

THF-312: remove menu cache

---

pages/api/events.ts
src/components/ContentMapper.tsx
src/components/events/EventList.tsx
src/components/mapEmbedded/MapEmbedded.tsx
src/components/pageTemplates/NodeTprUnitPage.tsx
src/lib/client-api.ts
src/lib/params.ts
src/lib/ssr-api.ts
src/lib/types.ts

- Events on Unit page displays events only for that location
- Updated method for component's props for code standard

THF-308: Adding events option to have display for unit only.

---

pages/[...slug].tsx
src/lib/helpers.ts

- Fixes broken breadcrumb on non-default languages

THF-333: Fixed breadcrumb on other langs than default.

---

src/components/pageTemplates/NodeLandingPage.tsx
styles/globals.scss

- Adds new wrapper class for Landing pages to get icons working for links.

THF-327: Fixing missing icons for links on Landing pages.

---

pages/api/news.ts
pages/api/units.ts
src/components/ContentMapper.tsx
src/components/events/EventList.tsx
src/components/news/NewsList.tsx
src/components/pageTemplates/NodeArticlePage.tsx
src/components/pageTemplates/NodeBasicPage.tsx
src/components/pageTemplates/NodeLandingPage.tsx
src/components/tprUnits/UnitsList.tsx
src/lib/client-api.ts
src/lib/ssr-api.ts
src/lib/types.ts

- Includes issues THF-346 & THF-341

THF-346: Selected language handling

---

package.json
pages/[...slug].tsx
pages/_app.tsx
pages/cookies.tsx
pages/index.tsx
src/components/navigation/Footer.tsx
src/hooks/useAnalytics.ts
src/lib/helpers.ts
styles/globals.scss
yarn.lock

- Adds HDS Cookie Consents (Modal + Page)
- Removes React Cookie Consents
- Includes cookie info for tyollisyyspalvelut.hel.fi
- User is able to change cookie settings and view info about stored cookies

THF-231: Cookie consents update

---

src/components/navigation/navigation.module.scss

- THF-362: Fixes orange color flash on page load
- THF-365: Fixes orange color on active menu item when navigating with keyboard

THF-362: Fixing colors in navigation

---

cache-headers.js
pages/sitemap.xml.js
public/robots.txt
tsconfig.json

THF-19: Sitemap

---

src/components/pageTemplates/NodeTprUnitPage.tsx
src/components/pageTemplates/tprUnitPage.module.scss

- Unit's contact information is now displayed within content area on mobile

THF-372: Updating Unit page layout for mobile.

---

next-i18next.config.js
package.json
pages/[...slug].tsx
pages/api/events-search.ts
pages/api/preview.tsx
pages/api/revalidate.ts
pages/index.tsx
yarn.lock

- Update Next version
- Fix typings with new Next version
- Add on demand revalidation
**How to test**
run
```
yarn build
yarn start
```
- Checkout the related Drupal PR
- Open page in incognito mode
- Update the page in Drupal with changes you can track
- Open the page in incognito mode
- You should not see the changes yet
- Go to: https://drupal-tyollisyyspalvelut-helfi.docker.so/admin/reports/dblog
- Check Notice message that starts with "Revalidating page at " (It doesn't work in the container because it can't connect to localhost.)
- Copy the localhost URL and paste it to your browser
- Go to the page in incognito mode. Page should be revalidated and you should see the changes.

THF-X: on demand revalidation

---

src/components/accordion/Accordion.tsx

- Translated close button for accordions

THF-358: Adding translated close button.

---

styles/globals.scss

- This should fix production env React & Share styling issues
- Uses official guide as template found from R&S website

THF-373: React & Share CSS update by the official guide.

---

pages/api/events-search.ts
src/components/events/EventList.tsx
src/components/pageTemplates/NodeEventPage.tsx
src/components/pageTemplates/eventPage.module.scss
src/lib/params.ts
src/lib/types.ts

- Street address for events on listing page
- Street address and map link on event page

THF-330: Event street address

---

pages/[...slug].tsx

Rebuilld only landing pages in staging.

Remove rebuilds in staging

---

pages/_app.tsx

- Hide cookie consent banner when on preview mode in Drupal

THF-389: Adding check on preview mode for cookie banner.

---

src/components/events/EventList.tsx

- Fixes missing addition for event lists on short format

THF-330: Adding missing street address to short event list.

---

src/components/events/EventList.tsx

- Fixes error on listing when event had a tag of "undefined"
- Error occurred when increasing events amount on the list via add button

THF-385: Fixes event listing error.

---

styles/globals.scss

- This is a tryout to fix the production version of React and Share component styles

THF-373: RnS components styles based for production

---

src/hooks/useAnalytics.ts

- Fixes an issue with cookie consents not accepted infobox where the box didn't hide when accepting the cookies.

THF-418: Adding page refresh when cookies are accepted

---

pages/api/search.ts
pages/search.tsx
public/locales/en/common.json
public/locales/sv/common.json
src/lib/types.ts
styles/globals.scss

- Suggestions for the search input
- Content type badge fixes for News

THF-170: Search suggestions

---

next.config.js
package.json
pages/_error.tsx
sentry.client.config.js
sentry.properties
sentry.server.config.ts
yarn.lock

- Set Sentry monitoring for Staging to look up for errors on the environment

THF-378: Implementing Sentry monitoring.

---

pages/api/events-tags.ts

Includes the following changes
- THF-413: Fixing search index query
- THF-413: Fixing sorting

Release jan 2023 [missing commits]

---

src/components/banner/banner.module.scss
src/components/navigation/Header.tsx
src/lib/helpers.ts

- Fix print button visibility
- Hide graphics on printing

THF-442: Printing functionality (updates)

---

src/components/accordion/accordion.module.scss
src/components/consentInfo/ConsentInfo.tsx
src/components/consentInfo/consentInfo.module.scss
src/components/events/events.module.scss
src/components/navigation/navigation.module.scss
styles/globals.scss

**To test**
- Check that all relevant commits are included

Merge release 2.2 to main

---

src/components/navigation/Header.tsx

THF-446: language selection null check

---

src/lib/ssr-api.ts

Fetching wasn't working  so we now fetch help with Drupal Server.
How to test:
- see that `yarn build` doesn't give errors
- see pages:
- http://localhost:3000/en/current-matters/events - page has events
- http://localhost:3000/en/current-matters/news - page has news
- http://localhost:3000/en/contact-information/offices -page has office card with images.

THF-496: Add drupal server to fetch

---

pages/api/events-search.ts
pages/api/events-tags.ts
src/components/events/Events.tsx
src/lib/client-api.ts

**To test**
- Checkout branch
- Check that the events list page localisation works
- Read code change

THF-0: Fix  locale handling in events search

---

src/components/navigation/Footer.tsx

Addes HDS somelinks to the footer. 
How to test:
- Test that links lead to right social media Platform.
- Test that the footer still looks good on all screen size 
- Test accessibility

THF-465: Add some icons

---

public/locales/en/common.json
public/locales/fi/common.json
public/locales/ru/common.json
public/locales/so/common.json
public/locales/sv/common.json
public/locales/uk/common.json
src/components/pageTemplates/NodeTprUnitPage.tsx
src/lib/params.ts

Added email to office Ohjaamo.
How to test. 
- Go to page [/ohjaamo](http://localhost:3000/ohjaamo)
- See that the page have (on the left side of the page) email before the phone number
- Check also other offices they shouldn't have email on the page.

THF-497: add email to Ohjaamo

---

pages/404.tsx
pages/api/events-search.ts
pages/api/events-tags.ts
src/components/events/Events.tsx
src/components/navigationComponents/navigationComponents.module.scss
src/lib/helpers.ts

fixing sonar could bugs
How to test:
- Test the filter tag aria-checked changes when toggling the filter tag buttons. Page /ajankohtaista/tapahtumat
-  Check the global button still working and looks the same.

THF-445: sonardCllound corrections

---

pages/api/events-search.ts

fixing sonar could bugs
How to test:
Test the filter tag aria-checked changes when toggling the filter tag buttons. Page /ajankohtaista/tapahtumat
Check the global button still working and looks the same.

THF-445: refactoring code

---

pages/api/events-search.ts

fixing sonar could bugs
How to test:
Test the filter tag aria-checked changes when toggling the filter tag buttons. Page /ajankohtaista/tapahtumat
Check the global button still working and looks the same.

Thf 445 sonar cloud code correction

---

src/components/navigation/Breadcrumb.tsx
src/components/navigation/Header.tsx
src/components/navigationComponents/LanguageSelect.tsx
src/components/navigationComponents/MobileNavigation.tsx
src/components/navigationComponents/Navigation.tsx
src/lib/types.ts

Fix preview:
How to test:
Test Drupal site:
-login to Drupal
- URL needs to follow navigation, breadcrumbs and language selection .
Test Next site 
- URL needs to follow navigation, breadcrumbs and language selection. Make sure that in Next.js site you stay on Next.js site. Meaning you don't end up to Drupal site.

THF-469: preview fix

---

pages/api/events-search.ts
pages/sitemap.xml.js
src/components/ContentMapper.tsx
src/components/events/Events.tsx
src/components/navigation/Sidebar.tsx
src/lib/helpers.ts

https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&id=City-of-Helsinki_employment-services-ui
- Added return null to Sitemap
- events-search.ts Moved functions outside the component
- Helper.ts changed typescript any to actual values
- ContentMapper added semicolons
How to test:
- Test filters on event page carefully.
- Test breadcrumb - Test news page, event page, some menu page and create new basic page.

Thf 445 sonar cloud code correction critical

---

src/components/contactInfo/ContactInfo.tsx
src/components/events/EventList.tsx
src/components/listOfLinks/ListOfLinks.tsx
src/components/navigation/Breadcrumb.tsx
src/components/navigation/Footer.tsx
src/components/navigation/Header.tsx
src/components/navigation/Sidebar.tsx
src/components/navigationComponents/LanguageSelect.tsx
src/components/navigationComponents/MobileNavigation.tsx
src/components/navigationComponents/Navigation.tsx
src/components/news/NewsList.tsx
src/components/pageTemplates/NodeEventPage.tsx
src/components/tprUnits/UnitsList.tsx
src/lib/ssr-api.ts

- Removed unused imports
- TypeScript refactoring
- Changed logical or (`||`) to nullish coalescing operator (`??`) 
- Changen sideMap map function to foreach because the first value doesn't return anything
- Cookies url handling changed to switch loop
What to test:
-Try footer cookies link in every language. Go to front page and see that you end up Finnish Cookie page when you language is Finnish, To Swedish is you language is Swedish and to English page if your language is anything else than previously mentioned languages.
- Try office list page and see that there is no changes
- See that the side bar works as before.

THF-445: TypeScript refactoring

---

public/locales/en/common.json
public/locales/fi/common.json
public/locales/sv/common.json
src/components/pageTemplates/NodeArticlePage.tsx
src/lib/ssr-api.ts

Added partner job to news lift up filter.
How to test
- Test this branch with Drupal branch https://github.com/City-of-Helsinki/drupal-employment-services/pull/146
- Add follow the indstructions on that branch.

THF-562: Add filter option partner-jobs

---

public/locales/sv/common.json

THF-562: Change the Swedish text

---

src/components/pageTemplates/NodeEventPage.tsx
src/lib/params.ts

Added fields publisher and provider
- Test with branch https://github.com/City-of-Helsinki/drupal-employment-services/pull/157
- Go to any event and see if there is provider and publisher on place.

Thf 534 publisher and provider UI

---

src/components/events/EventList.tsx
src/components/events/Events.tsx
src/components/pageTemplates/NodeEventPage.tsx

Added empty array to alt if atl text not exist.
- Choose one event and remove the Alt from the image.
- You should not get errors
- see also event list http://localhost:3000/ajankohtaista/tapahtumat

THF-598: added empty string if alt missing

---

next.config.js

Redirected basic page to new article content types
- Test links below they should end up to the article pages. Restart Next.js project before testing.
```
source: '/avaa-urasi-kouluttautumalla-tai-yrittajana',
destination: '/ajankohtaista/uutiskirjeet/avaa-urasi-kouluttautumalla-tai-yrittajana',
```
```
source: '/vahvista-osaamistasi-varmista-paikkasi-tyomarkkinoilla',
destination: '/ajankohtaista/uutiskirjeet/vahvista-osaamistasi-varmista-paikkasi-tyomarkkinoilla',
```
```
source: '/nyhetsbrev-december-2022',
destination: '/aktuellt/nyhetsbrev/nyhetsbrev-december-2022',
```
```
source: '/experts-are-needed-learn-new-skills-and-grow-your-expertise',
destination: '/current-matters/newsletters/experts-are-needed-learn-new-skills-and-grow-your-expertise',
```
```
source: …
```

THF-570: redirect news letters

---

src/components/accordion/Accordion.tsx
src/components/accordion/AccordionWithIcon.tsx
src/components/accordion/accordion.module.scss
src/components/events/EventList.tsx
src/components/events/Events.tsx
src/components/layout/Layout.tsx
src/components/pageTemplates/NodeTprUnitPage.tsx

Changed place of the accessibility accordion element.
- Go to page https://drupal-tyollisyyspalvelut-helfi.docker.so/kamppi
- Edit
- Add new text paragraph below the first text paragraph
- Save
- You should see the accessibility accordion element between you new element and the first paragraph on the page.

Thf 600 tpr unit accessibility

---

src/hooks/useAnalytics.ts

Changed name React & Share to Askem
-Test all cookies pages (en, fi ja sv) http://localhost:3000/cookies you shouldn't have react and share in cookies page.

THF-490: Change name

---

src/components/navigationComponents/LanguageSelect.tsx

Changed Ukrainian to language switcher.
- Go to http://localhost:3000//ua/frontpage
- Check that you have Українська both in global selection and the next to Suomi, Svenska and English. Not like in the picture.

THF-620: Change au name to language selection

---

src/lib/ssr-api.ts

Added status filter and locale filter to short event list paragraph
- Go local http://localhost:3000/
- You should have events in the events list paragraph.
- check also the tpr unit pages example http://localhost:3000/pasila you should have 2 event in this page.

THF-621: add unpublished and locale filters to api json call

---

pages/api/search.ts

Added field_search_keyword_text^90 and given boost 90. 90 gets the field_search_keyword_text boosted to second place after search_keywords.
- Follow the testing instructions from https://github.com/City-of-Helsinki/drupal-employment-services/pull/172

THF-453: change search index boost and add keyword_text

---

src/lib/types.ts

added missing type.
- run yarn build and see you don't get errors.

THF-610: corrent missing type

---

src/components/ContentMapper.tsx
src/components/link/IconLink.tsx
src/components/link/link.module.scss
src/components/linkwithIcon/LinkWithIcon.tsx
src/components/linkwithIcon/linkWithIcon.module.scss
src/lib/drupalApiTypes.js
src/lib/params.ts

Added link with icon component
- start testing with branch https://github.com/City-of-Helsinki/drupal-employment-services/pull/175
- The accordion should look the same as it looks in  page https://tyollisyyspalvelut.hel.fi/asiointi/lomakkeet

Thf 326 link with icon UI

---

src/components/pageTemplates/NodeBasicPage.tsx

Added length check to side bar. If breadcrumb length if over 4 sidebar is hidden.
- compare http://localhost:3000/digityoelamaa vs https://tyollisyyspalvelut.hel.fi/digityoelamaa
- local environment you should have side bar. 
- Check a few other pages to verify that they remain the same.

Thf 318 sidebar length

---

src/components/eventsComponents/DropdownFilter.tsx

THF-637: change type

---

pages/api/events-search.ts
src/components/events/Events.tsx
src/components/events/events.module.scss
src/components/eventsComponents/ButtonFilter.tsx
src/components/news/NewsList.tsx
src/lib/helpers.ts

- Updating the hover color
- Implemented distinct keys for events and news, allowing them run in same page. 
- Implemented a logic to get the results when either or both event and language tags are selected.
- Ensured that if the language tag doesn't get result, the button will remain selected.
- Change tag fetching so that if something fails not all request fails
**Test Hover Color:**
- Verify that filter buttons has a grey color when not selected, and hovered over.
**Create Page with News and Events Lists:**
- Create page with both news and events lists and page runs without any issues.
-
**Select Event Tags and Confirm Result Display:**
Validate that selecting event tags displays results, such as "10/86," providing rather than a singular number.
**Test for Arabic Language:**
- Check …

Thf 637 other languages index UI

---

pages/api/events.ts
src/components/events/EventList.tsx

- Given condition to size. When fetching with location id we will fetch 2 otherwise 3.
- Changed url (URL is coming with langcode if exist)
- Go to [kamppi](http://localhost:3000//kamppi)
- Verify that the offices has only 2 events
- Got o frontpage  [frontpage](http://localhost:3000//)
- Se that the event list links are working

THF-637: add condition to events fetch and link to event
